### ISSUE TITLE
list区域的上拉和下拉

### ISSUE THREAD

**Issue by xuelinglong** [xuelinglong/Chinese-community#7]
list区域是一个整体，上拉和下拉是这一部分的需求，既然要让页面可以自由组合，那么把list区域放在其他页面的时候也应该能够实现所带有的上拉下拉效果，因此我之前的方案把上拉下拉组件写在topic.vue中的container外面，并且使用的是loadmore组件的上拉效果加上infinite scroll组件的滑动加载效果，导致上拉下滑有时会出现冲突。

**Comment by xuelinglong** [comment]
现在我把loadmore组件放在list.vue，配置好以后发现上拉下拉效果都可以实现，但是也出现了新的bug：1.因为topics.vue里面包含6个tab-container-item（即包含6个不同的list组件），此时页面初始渲染时会执行6次获取数据的操作（FETCH_TOPICS），当我把tab-container去掉，改成<list :tabName="selected"></list>时就没有这个问题了。2.上拉刷新的字样会显示在没有触发loadBottom时出现在界面中：loadmore组件有一个API：autoFill:true初始化时自动检测它的高度是否撑满容器，如果不能则会调用loadBottom方法；但是感觉最有可能的事我的布局写的不合理，本来“上拉刷新”应该隐藏的，现在出现了。

**Comment by xuelinglong** [comment]
经过测试发现把autoFill改为false，“上拉刷新”还是没有被隐藏

**Comment by zymxxxs** [comment]
上拉先不要使用了，使用 `Infinite scroll` 代替吧。

**Comment by zymxxxs** [comment]
`下拉刷新` 配合 `Infinite scroll` 应该也可以满足需求。

**Comment by zymxxxs** [comment]
以后记录 `issue`，记得使用 md 格式，那么一大坨文字，看着难受。
